from typing import Optional
from typing_extensions import Protocol

from src.domain.email_session import EmailSession


class SessionStore(Protocol):
    def get_email(self, user_id: int) -> Optional[str]: ...
    def get_deadline(self, user_id: int) -> Optional[float]: ...
    def find_user(self, email: str) -> Optional[int]: ...
    def register(self, session: EmailSession, deadline: float) -> None: ...
    def remove(self, user_id: int) -> None: ...
    def has_active(self) -> bool: ...
